services:
  odoodb:
    image: postgres:15
    restart: always  # This ensures it restarts on failure or system reboot
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  odoo:
    build:
      context: .
      dockerfile: Dockerfile # Optional if it's named Dockerfile
    restart: always  # This ensures it restarts on failure or system reboot
    depends_on:
      - odoodb
    ports:
      - "8069:8069"
    